<a href="https://colab.research.google.com/github/Shiv-Sai20111018/eos-ai-workshop/blob/main/Session2_PartA-%20colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("EOS")

EOS


Workshop

In [ ]:
name = "Aryan"
age = 16
print(name)           # Aryan
print(age)            # 16
print("Hello", name)  # Hello Aryan

Aryan
16
Hello Aryan


In [ ]:
print(type(True))

<class 'bool'>


In [ ]:
name = "Aryan"
greeting = "Hi " + name
print(greeting)

Hi Aryan


In [ ]:
# Arithmetic Operators in Python

a = 10
b = 3

# Addition
print("Addition:", a + b)       # 10 + 3 = 13

# Subtraction
print("Subtraction:", a - b)    # 10 - 3 = 7

# Multiplication
print("Multiplication:", a * b) # 10 * 3 = 30

# Division (float result)
print("Division:", a / b)       # 10 / 3 = 3.333...

# Floor Division (integer result)
print("Floor Division:", a // b) # 10 // 3 = 3

# Modulus (remainder)
print("Modulus:", a % b)        # 10 % 3 = 1

# Exponentiation (power)
print("Exponent:", a ** b)      # 10^3 = 1000

Addition: 13
Subtraction: 7
Multiplication: 30
Division: 3.3333333333333335
Floor Division: 3
Modulus: 1
Exponent: 1000


In [ ]:
name = "Aryan"
age = 16
print(f"My name is {name} and I am {age}")

My name is Aryan and I am 16


In [ ]:
name = input("Enter your name: ")
print(f"Hello {name}")

KeyboardInterrupt: Interrupted by user

In [ ]:
subjects = ["Maths", "Physics", "CS","Maths", "Physics", "CS","Maths", "Physics", "CS","Maths", "Physics", "CS","Maths", "Physics", "CS","Maths", "Physics", "CS"]


len_sub = len(subjects)

print(len_sub)

18


In [ ]:
# Access by index (starts at 0!)
print(subjects[0])      # Maths
print(subjects[-1])     # CS  (negative = from end)


# Change items
subjects.append("Chemistry")    # add to end
subjects.remove("Physics")       # remove by value
print(subjects)  # ['Maths', 'CS', 'Chemistry']

Maths
CS
['Maths', 'CS', 'Maths', 'Physics', 'CS', 'Maths', 'Physics', 'CS', 'Maths', 'Physics', 'CS', 'Maths', 'Physics', 'CS', 'Maths', 'Physics', 'CS', 'Chemistry']


In [ ]:

student = {
    "name": "Priya",
    "grade": 11,
    "score": 92,
    "subjects": ["Maths", "Physics", "CS"]
}

# Look up by key
print(student["name"])       # Priya
print(student["subjects"])   # ['Maths', 'Physics', 'CS']

# Add or change
student["city"] = "Chennai"
student["score"] = 95

# Check if a key exists
print("age" in student)      # False
print(student.keys())        # dict_keys(['name', 'grade', ...])

print(student)

Priya
['Maths', 'Physics', 'CS']
False
dict_keys(['name', 'grade', 'score', 'subjects', 'city'])
{'name': 'Priya', 'grade': 11, 'score': 95, 'subjects': ['Maths', 'Physics', 'CS'], 'city': 'Chennai'}


In [ ]:

students = {"Rohan": 85, "Priya": 92, "Aryan": 78}

print(students["Priya"])
print(len(students))
print(list(students.keys()))

students["Meera"] = 90
print(students["Meera"])

92
3
['Rohan', 'Priya', 'Aryan']
90


In [ ]:
score = 85

if score >= 90:
    grade = "A"
elif score >= 75:
    grade = "B"
elif score >= 60:
    grade = "C"
elif score >= 50:
    grade = "D"
else:
    grade = "F"

print(f"Score {score} → Grade {grade}")

Score 85 → Grade B


In [ ]:
subjects = ["Maths", "Physics", "CS"]

# Iterate over a list
for x in subjects:
    print(f"Studying {x}")

Studying Maths
Studying Physics
Studying CS


In [ ]:
scores = {"Rohan": 85, ,"Priya": 92,"Priya": 92,"Priya": 92}
for name, score in scores.items():
    print(f"{name}: {score}")

Rohan: 85
Priya: 92


In [ ]:
for a in range(5):
    print(a)        # 0 1 2 3 4

0
1
2
3
4


In [ ]:
def average(nums):
    return sum(nums) / len(nums)

print(average([88, 92, 76]))
print(average([85, 90, 78]))
print(average([95, 88, 91]))

85.33333333333333
84.33333333333333
91.33333333333333


In [ ]:
def add(a, b):
    return a + b

In [ ]:
add(10,20)

30

In [ ]:
import time

py_list = list(range(1_000_000))
start = time.time()

result = [x * 2 for x in py_list]

print(f"List: {time.time()-start:.4f}s")
# List: 0.0812s

List: 0.0896s


In [ ]:
import numpy as np
import time

np_arr = np.arange(1_000_000)
start = time.time()

result = np_arr * 2

print(f"NumPy: {time.time()-start:.4f}s")
# NumPy: 0.0018s

NumPy: 0.0240s


In [ ]:
import numpy as np

ones = np.ones((2, 4))

print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np

np.random.seed(42)

print(np.random.rand())
print(np.random.rand())
print(np.random.rand())

0.3745401188473625
0.9507143064099162
0.7319939418114051


In [ ]:
import numpy as np

scores = np.array([88, 92, 76, 85, 90])

scores[0] = scores[0] + 5   # add 5 only to first element
print(scores)

[93 92 76 85 90]


In [ ]:
import numpy as np

scores = np.array([88, 92, 76, 85, 90])

print(scores.mean())    # 86.2      ← average
print(scores.std())     # 5.56      ← standard deviation (spread)
print(scores.max())     # 92
print(scores.min())     # 76
print(scores.sum())     # 431

# Where's the max/min?
print(np.argmax(scores))  # 1       ← index of the top scorer (92)
print(np.argmin(scores))  # 2       ← index of the lowest (76)

# Sort
print(np.sort(scores))

86.2
5.6
92
76
431
1
2
[76 85 88 90 92]


In [ ]:
print(-np.sort(-scores))

[92 90 88 85 76]


In [ ]:
scores = np.array([10, 20, 30, 40])

print(np.median(scores))

25.0


In [ ]:
import numpy as np

scores = np.array([88, 92, 76, 85, 90])

print(scores[:1])

[88]


In [ ]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix.shape)         # (3, 3)

# Flatten to 1D
flat = matrix.flatten()
print(flat)                 # [1 2 3 4 5 6 7 8 9]
print(flat.shape)           # (9,)

(3, 3)
[1 2 3 4 5 6 7 8 9]
(9,)


In [ ]:
print(flat[2:6])

[3 4 5 6]
